export const FETCH_GIFT_CARD_REQUEST_LIST = "FETCH_GIFT_CARD_REQUEST_LIST";
export const FETCH_GIFT_CARD_REQUEST_LIST_SUCCESS = "FETCH_GIFT_CARD_REQUEST_LIST_SUCCESS";
export const FETCH_GIFT_CARD_REQUEST_LIST_FAILURE = "FETCH_GIFT_CARD_REQUEST_LIST_FAILURE";
