export const FETCH_GIFT_CARD_REQUEST_LIST = "FETCH_GIFT_CARD_REQUEST_LIST";
export const FETCH_GIFT_CARD_REQUEST_LIST_SUCCESS = "FETCH_GIFT_CARD_REQUEST_LIST_SUCCESS";
export const FETCH_GIFT_CARD_REQUEST_LIST_FAILURE = "FETCH_GIFT_CARD_REQUEST_LIST_FAILURE";

export const FETCH_GIFT_CARD_INTEGRATION_LIST = "FETCH_GIFT_CARD_INTEGRATION_LIST";
export const FETCH_GIFT_CARD_INTEGRATION_LIST_SUCCESS = "FETCH_GIFT_CARD_INTEGRATION_LIST_SUCCESS";
export const FETCH_GIFT_CARD_INTEGRATION_LIST_FAILURE = "FETCH_GIFT_CARD_INTEGRATION_LIST_FAILURE";

export const SET_GIFT_CARD_REQUEST_INTEGRATION = "SET_GIFT_CARD_INTEGRATION";
export const SET_GIFT_CARD_REQUEST_AMOUNT = "SET_GIFT_CARD_REQUEST_AMOUNT";
export const SET_GIFT_CARD_REQUEST_STEP_BACK = "SET_GIFT_CARD_REQUEST_STEP_BACK";
export const SET_GIFT_CARD_REQUEST_RESET_DATA = "SET_GIFT_CARD_REQUEST_RESET_DATA";

export const POST_GIFT_CARD_REQUEST = "POST_GIFT_CARD_REQUEST";
export const POST_GIFT_CARD_REQUEST_SUCCESS = "POST_GIFT_CARD_REQUEST_SUCCESS";
export const POST_GIFT_CARD_REQUEST_FAILURE = "POST_GIFT_CARD_REQUEST_FAILURE";
