#!/usr/bin/env bash

echo "docker run "${ENVIRONMENT_NAME-development}${SERVICE-nginx}

docker-compose -f docker-compose-dev.yml run -e ENVIRONMENT_NAME=${ENVIRONMENT_NAME-development} --rm --use-aliases --service-ports ${SERVICE-nginx}