export const FETCH_ADMIN_GIFT_CARD_REQUEST_LIST =
  "FETCH_ADMIN_GIFT_CARD_REQUEST_LIST";
export const FETCH_ADMIN_GIFT_CARD_REQUEST_LIST_SUCCESS =
  "FETCH_ADMIN_GIFT_CARD_REQUEST_LIST_SUCCESS";
export const FETCH_ADMIN_GIFT_CARD_REQUEST_LIST_FAILURE =
  "FETCH_ADMIN_GIFT_CARD_REQUEST_LIST_FAILURE";

export const FETCH_ADMIN_GIFT_CARD_REQUEST = "FETCH_ADMIN_GIFT_CARD_REQUEST";
export const FETCH_ADMIN_GIFT_CARD_REQUEST_SUCCESS =
  "FETCH_ADMIN_GIFT_CARD_REQUEST_SUCCESS";
export const FETCH_ADMIN_GIFT_CARD_REQUEST_FAILURE =
  "FETCH_ADMIN_GIFT_CARD_REQUEST_FAILURE";

export const FETCH_ADMIN_GIFT_CARD_REQUEST_USER =
  "FETCH_ADMIN_GIFT_CARD_REQUEST_USER";
export const FETCH_ADMIN_GIFT_CARD_REQUEST_USER_SUCCESS =
  "FETCH_ADMIN_GIFT_CARD_REQUEST_USER_SUCCESS";
export const FETCH_ADMIN_GIFT_CARD_REQUEST_USER_FAILURE =
  "FETCH_ADMIN_GIFT_CARD_REQUEST_USER_FAILURE";

export const FULFILL_ADMIN_GIFT_CARD_REQUEST =
  "FULFILL_ADMIN_GIFT_CARD_REQUEST";
export const FULFILL_ADMIN_GIFT_CARD_REQUEST_SUCCESS =
  "FULFILL_ADMIN_GIFT_CARD_REQUEST_SUCCESS";
export const FULFILL_ADMIN_GIFT_CARD_REQUEST_FAILURE =
  "FULFILL_ADMIN_GIFT_CARD_REQUEST_FAILURE";

export const DECLINE_ADMIN_GIFT_CARD_REQUEST =
  "DECLINE_ADMIN_GIFT_CARD_REQUEST";
export const DECLINE_ADMIN_GIFT_CARD_REQUEST_SUCCESS =
  "DECLINE_ADMIN_GIFT_CARD_REQUEST_SUCCESS";
export const DECLINE_ADMIN_GIFT_CARD_REQUEST_FAILURE =
  "DECLINE_ADMIN_GIFT_CARD_REQUEST_FAILURE";
