sudo: required
services:
  - docker

# before_install:
#   - ./auto/api_service/apitest
before_install:
  - >-
    openssl aes-256-cbc 
    -K $encrypted_8ebb1ef83f64_key 
    -iv $encrypted_8ebb1ef83f64_iv 
    -in github_deploy_key.enc 
    -out github_deploy_key 
    -d
  - chmod 600 github_deploy_key
  - eval $(ssh-agent -s)
  - ssh-add github_deploy_key

script:
  - ./auto/api_service/test || travis_terminate 1;
  - ./auto/clean-up || travis_terminate 1;
  - ./auto/api_service/apitest || travis_terminate 1;
  - docker build -t raso354/santa_api_service ./api_service || travis_terminate 1;
  - docker build -t raso354/santa_nginx ./nginx || travis_terminate 1;
  - docker build -t raso354/santa_client_app ./client_app || travis_terminate 1;
  # script:
  #   - docker run USERNAME/react-test npm test -- --coverage

after_success:
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push Images
  - docker push raso354/remotesanta:santa_client_app
  - docker push raso354/remotesanta:santa_nginx
  - docker push raso354/remotesanta:santa_api_service
