sudo: required
services:
  - docker

# before_install:
#   - ./auto/api_service/apitest
before_install:
  - >-
    openssl aes-256-cbc 
    -K $encrypted_8ebb1ef83f64_key 
    -iv $encrypted_8ebb1ef83f64_iv 
    -in github_deploy_key.enc 
    -out github_deploy_key 
    -d
  - chmod 600 github_deploy_key
  - eval $(ssh-agent -s)
  - ssh-add github_deploy_key

script:
  - ./auto/api_service/test
  - ./auto/clean-up
  - ./auto/api_service/apitest
  # script:
  #   - docker run USERNAME/react-test npm test -- --coverage

after__success:
  - docker build -t raso354/santa_client_app ./client_app
  - docker build -t raso354/santa_nginx ./nginx
  - docker build -t raso354/santa_api_service ./api_service
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | dockker login -u "$DOCKER_ID" --password-stdin
  # Push Images
  - docker push raso354/santa_client_app
  - docker push raso354/santa_nginx
  - docker push raso354/santa_api_service
