version: "3"
services:
  client_app_full:
    image: "raso354/preprod_remotesanta_client_app"
    ports:
      - "3000:3000"
  api_full:
    image: "raso354/preprod_remotesanta_santa_api_service"
    environment:
      PORT: "8090"
      AWS_COGNITO_USER_POOL_ID: ${AWS_COGNITO_USER_POOL_ID}
      AWS_COGNITO_CLIENT_ID: ${AWS_COGNITO_CLIENT_ID}
      AWS_COGNITO_AUTHORITY: ${AWS_COGNITO_AUTHORITY}
      AWS_SES_SMTP_HOST: ${AWS_SES_SMTP_HOST}
      AWS_SES_SMTP_USERNAME: ${AWS_SES_SMTP_USERNAME}
      AWS_SES_SMTP_PASSWORD: ${AWS_SES_SMTP_PASSWORD}
      AWS_SQS_QUEUE_URL_FIRST: https://sqs.eu-west-3.amazonaws.com/420116094867/first-queue.fifo
      AWS_SQS_QUEUE_URL_FIRST_FAILED: https://sqs.eu-west-3.amazonaws.com/420116094867/dead-first-queue.fifo
      AWS_SQS_QUEUE_URL_USER_INVITE_IMPORT: https://sqs.eu-west-3.amazonaws.com/420116094867/user-invite-bulk-create.fifo
      AWS_SQS_QUEUE_URL_USER_INVITE_IMPORT_FAILED: https://sqs.eu-west-3.amazonaws.com/420116094867/dead-user-invite-bulk-create.fifo
      EMAIL_FROM: ${EMAIL_FROM}
      DATABASE_URL: ${DATABASE_URL}
      AWS_S3_BUCKET_GIFT_CARDS: ${AWS_S3_BUCKET_GIFT_CARDS}
      AWS_S3_ENDPOINT: ${AWS_S3_ENDPOINT}
      AWS_REGION: ${AWS_REGION}
      FE_BASE_URL: ${FE_BASE_URL}
      NODE_ENV: preprod
    ports:
      - "8090:8090"
  nginx:
    depends_on:
      - api_full
      - client_app_full
    links:
      - api_full
      - client_app_full
    image: "raso354/preprod_remotesanta_santa_nginx"
    restart: always
    ports:
      - "80:80"
      - "81:81"
