version: "3"
services:
  client_app_full:
    image: "raso354/remotesanta_client_app"
    ports:
      - "3000:3000"
  api_full:
    image: "raso354/remotesanta_santa_api_service"
    environment:
      PORT: "8090"
      AWS_COGNITO_USER_POOL_ID: ${AWS_COGNITO_USER_POOL_ID}
      AWS_COGNITO_CLIENT_ID: ${AWS_COGNITO_CLIENT_ID}
      AWS_COGNITO_AUTHORITY: ${AWS_COGNITO_AUTHORITY}
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "8090:8090"
  nginx:
    depends_on:
      - api_full
      - client_app_full
    links:
      - api_full
      - client_app_full
    image: "raso354/remotesanta_santa_nginx"
    ports:
      - "80:80"
