version: "3"
services:
  client_app_full:
    image: "raso354/remotesanta_client_app"
    hostname: client_app_full
  api_full:
    image: "raso354/remotesanta_santa_api_service"
    hostname: api_full
    environment:
      PORT: "8090"
  nginx:
    image: "raso354/remotesanta_santa_nginx"
    hostname: nginx
    ports:
      - "80:80"
