version: "3"
services:
  client_app_full:
    image: "raso354/remotesanta_client_app"
    hostname: client_app_full
  api_full:
    image: "raso354/remotesanta_santa_api_service"
    mem_limit: 128m
    hostname: api_full
    environment:
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  nginx:
    image: "raso354/remotesanta_santa_nginx"
    hostname: nginx
    ports:
      - "80:80"
