version: "3"
services:
  client_app_full:
    image: "raso354/remotesanta_client_app"
    environment:
      REACT_APP_BASE_URL: http://ec2-3-145-156-72.us-east-2.compute.amazonaws.com/
    ports:
      - "3000:3000"
  api_full:
    image: "raso354/remotesanta_santa_api_service"
    environment:
      PORT: "8090"
      AWS_COGNITO_USER_POOL_ID: ${AWS_COGNITO_USER_POOL_ID}
      AWS_COGNITO_CLIENT_ID: ${AWS_COGNITO_CLIENT_ID}
      AWS_COGNITO_AUTHORITY: ${AWS_COGNITO_AUTHORITY}
      AWS_SES_SMTP_HOST: ${AWS_SES_SMTP_HOST}
      AWS_SES_SMTP_USERNAME: ${AWS_SES_SMTP_USERNAME}
      AWS_SES_SMTP_PASSWORD: ${AWS_SES_SMTP_PASSWORD}
      EMAIL_FROM: ${EMAIL_FROM}
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "8090:8090"
  nginx:
    depends_on:
      - api_full
      - client_app_full
    links:
      - api_full
      - client_app_full
    image: "raso354/remotesanta_santa_nginx"
    ports:
      - "80:80"
