# docker-compose.yml

version: "3.8"
services:
  pg:
    image: postgres:13.5
    # restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=api-service-default
    volumes:
      - ./backup/:/mnt/backups/
    ports:
      - "5432:5432"

  # minio:
  #   image: minio/minio
  #     command: server /data/
  #     environment:
  #       MINIO_ACCESS_KEY: my_access_key
  #       MINIO_SECRET_KEY: my_secret_key
  #     ports:
  #       - 9000:9000
  #     volumes:
  #       - .docker/volumes/minio/:/data/

  pgtest:
    image: postgres:13.5
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=reward-service-test

  bare: &app
    image: node:16.15.1
    working_dir: /app
    command: yarn start:dev
    volumes:
      - ./api_service/:/app/
      - yarn-cache:/usr/local/share/.cache/yarn/v2
    environment:
      APP_VERSION: 0.1.0-snapshot
      PORT: 8090
      DATABASE_URL: postgres://myuser:mypassword@pg:5432/api-service-default

  api_full:
    <<: *app
    ports:
      - 8090:8090
    depends_on:
      - pg
      # - minio
    links:
      - pg
      # - minio

  client_app_bare: &fe_app # image: node:16.15.1
    working_dir: /app
    image: node:16.15.1
    command: yarn start
    volumes:
      - ./client_app/:/app/
      - yarn-cache-fe:/usr/local/share/.cache/yarn/v2

  client_app_full:
    <<: *fe_app
    environment:
      API_SERVICE_URL: http://localhost:3050/api/
      WDS_SOCKET_PORT: 0
    ports:
      - 3000:3000

  nginx:
    depends_on:
      - api_full
      - client_app_full
    links:
      - api_full
      - client_app_full
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - 3050:80

  apitest:
    <<: *app
    ports:
      - 8800:8800
    environment:
      DATABASE_URL: postgres://test:test@pgtest:5432/reward-service-test
    depends_on:
      - pgtest
      # - minio

volumes:
  yarn-cache: { external: true }
  yarn-cache-fe: { external: true }
