export const FETCH_CLAIM_POINTS_EVENT_LIST = "FETCH_CLAIM_POINTS_EVENT_LIST";
export const FETCH_CLAIM_POINTS_EVENT_LIST_SUCCESS = "FETCH_CLAIM_POINTS_EVENT_LIST_SUCCESS";
export const FETCH_CLAIM_POINTS_EVENT_LIST_FAILURE = "FETCH_CLAIM_POINTS_EVENT_LIST_FAILURE";
