export const FETCH_ADMIN_ORGANIZATION_TRANSACTION_LIST =
  "FETCH_ADMIN_ORGANIZATION_TRANSACTION_LIST";
export const FETCH_ADMIN_ORGANIZATION_TRANSACTION_LIST_SUCCESS =
  "FETCH_ADMIN_ORGANIZATION_TRANSACTION_LIST_SUCCESS";
export const FETCH_ADMIN_ORGANIZATION_TRANSACTION_LIST_FAILURE =
  "FETCH_ADMIN_ORGANIZATION_TRANSACTION_LIST_FAILURE";

export const POST_ADMIN_TO_ORG_TRANSACTION = "POST_ADMIN_TO_ORG_TRANSACTION";
export const POST_ADMIN_TO_ORG_TRANSACTION_SUCCESS =
  "POST_ADMIN_TO_ORG_TRANSACTION_SUCCESS";
export const POST_ADMIN_TO_ORG_TRANSACTION_FAILURE =
  "POST_ADMIN_TO_ORG_TRANSACTION_FAILURE";
