export const FETCH_ORGANIZATION = "FETCH_ORGANIZATION";
export const FETCH_ORGANIZATION_SUCCESS = "FETCH_ORGANIZATION_SUCCESS";
export const FETCH_ORGANIZATION_FAILURE = "FETCH_ORGANIZATION_FAILURE";

export const FETCH_ORG_TRANSACTION_LIST = "FETCH_ORG_TRANSACTION_LIST";
export const FETCH_ORG_TRANSACTION_LIST_SUCCESS =
  "FETCH_ORG_TRANSACTION_LIST_SUCCESS";
export const FETCH_ORG_TRANSACTION_LIST_FAILURE =
  "FETCH_ORG_TRANSACTION_LIST_FAILURE";

export const FETCH_ORG_USER_LIST = "FETCH_ORG_USER_LIST";
export const FETCH_ORG_USER_LIST_SUCCESS = "FETCH_ORG_USER_LIST_SUCCESS";
export const FETCH_ORG_USER_LIST_FAILURE = "FETCH_ORG_USER_LIST_FAILURE";
