#!/usr/bin/env bash
echo "creating volume"
docker volume create yarn-cache > /dev/null || true
docker volume create yarn-cache-fe > /dev/null || true

echo "yarn install"
docker-compose run --rm bare yarn install

echo "docker run "${ENVIRONMENT_NAME-development}${SERVICE-bare}
docker-compose run -e ENVIRONMENT_NAME=${ENVIRONMENT_NAME-development} --rm --use-aliases --service-ports ${SERVICE-bare} sh -c "${*}"
