export const SELF_SIGN_UP_REQUEST = "SELF_SIGN_UP_REQUEST";
export const SELF_SIGN_UP_SUCCESS = "SELF_SIGN_UP_SUCCESS";
export const SELF_SIGN_UP_FAILURE = "SELF_SIGN_UP_FAILURE";

export const FETCH_COMPLETEMENT_STEPS_REQUEST =
  "FETCH_COMPLETEMENT_STEPS_REQUEST";
export const FETCH_COMPLETEMENT_STEPS_SUCCESS =
  "FETCH_COMPLETEMENT_STEPS_SUCCESS";
export const FETCH_COMPLETEMENT_STEPS_FAILURE =
  "FETCH_COMPLETEMENT_STEPS_FAILURE";

export const POST_COMPLETEMENT_STEPS_REQUEST =
  "POST_COMPLETEMENT_STEPS_REQUEST";
export const POST_COMPLETEMENT_STEPS_SUCCESS =
  "POST_COMPLETEMENT_STEPS_SUCCESS";
export const POST_COMPLETEMENT_STEPS_FAILURE =
  "POST_COMPLETEMENT_STEPS_FAILURE";
