export const SELF_SIGN_UP_REQUEST = "SELF_SIGN_UP_REQUEST";
export const SELF_SIGN_UP_SUCCESS = "SELF_SIGN_UP_SUCCESS";
export const SELF_SIGN_UP_FAILURE = "SELF_SIGN_UP_FAILURE";

export const FETCH_COMPLETEMENT_STEPS_REQUEST =
  "FETCH_COMPLETEMENT_STEPS_REQUEST";
export const FETCH_COMPLETEMENT_STEPS_SUCCESS =
  "FETCH_COMPLETEMENT_STEPS_SUCCESS";
export const FETCH_COMPLETEMENT_STEPS_FAILURE =
  "FETCH_COMPLETEMENT_STEPS_FAILURE";

export const POST_COMPLETEMENT_STEPS_REQUEST =
  "POST_COMPLETEMENT_STEPS_REQUEST";
export const POST_COMPLETEMENT_STEPS_SUCCESS =
  "POST_COMPLETEMENT_STEPS_SUCCESS";
export const POST_COMPLETEMENT_STEPS_FAILURE =
  "POST_COMPLETEMENT_STEPS_FAILURE";

export const SET_OPEN_MODAL_STEP = "SET_OPEN_MODAL_STEP";
export const SET_CLOSE_MODAL_STEP = "SET_CLOSE_MODAL_STEP";

export const POST_PERSONAL_DETAILS_REQUEST = "POST_PERSONAL_DETAILS_REQUEST";
export const POST_PERSONAL_DETAILS_SUCCESS = "POST_PERSONAL_DETAILS_SUCCESS";
export const POST_PERSONAL_DETAILS_FAILURE = "POST_PERSONAL_DETAILS_FAILURE";

export const POST_SIGNUP_BONUS_REQUEST = "POST_SIGNUP_BONUS_REQUEST";
export const POST_SIGNUP_BONUS_SUCCESS = "POST_SIGNUP_BONUS_SUCCESS";
export const POST_SIGNUP_BONUS_FAILURE = "POST_SIGNUP_BONUS_FAILURE";

export const POST_PURCHASE_POINTS_REQUEST = "POST_PURCHASE_POINTS_REQUEST";
export const POST_PURCHASE_POINTS_SUCCESS = "POST_PURCHASE_POINTS_SUCCESS";
export const POST_PURCHASE_POINTS_FAILURE = "POST_PURCHASE_POINTS_FAILURE";

export const POST_BIRTHDAYS_SETUP_REQUEST = "POST_BIRTHDAYS_SETUP_REQUEST";
export const POST_BIRTHDAYS_SETUP_SUCCESS = "POST_BIRTHDAYS_SETUP_SUCCESS";
export const POST_BIRTHDAYS_SETUP_FAILURE = "POST_BIRTHDAYS_SETUP_FAILURE";
