export const FETCH_USER_INVITE_LIST = "FETCH_USER_INVITE_LIST";
export const FETCH_USER_INVITE_LIST_SUCCESS = "FETCH_USER_INVITE_LIST_SUCCESS";
export const FETCH_USER_INVITE_LIST_FAILURE = "FETCH_USER_INVITE_LIST_FAILURE";

export const POST_USER_INVITE = "POST_USER_INVITE";
export const POST_USER_INVITE_SUCCESS = "POST_USER_INVITE_SUCCESS";
export const POST_USER_INVITE_FAILURE = "POST_USER_INVITE_FAILURE";

export const CANCEL_USER_INVITE = "CANCEL_USER_INVITE";
export const CANCEL_USER_INVITE_SUCCESS = "CANCEL_USER_INVITE_SUCCESS";
export const CANCEL_USER_INVITE_FAILURE = "CANCEL_USER_INVITE_FAILURE";
