export const FETCH_USER_INVITE_LIST = "FETCH_USER_INVITE_LIST";
export const FETCH_USER_INVITE_LIST_SUCCESS = "FETCH_USER_INVITE_LIST_SUCCESS";
export const FETCH_USER_INVITE_LIST_FAILURE = "FETCH_USER_INVITE_LIST_FAILURE";

export const POST_USER_INVITE = "POST_USER_INVITE";
export const POST_USER_INVITE_SUCCESS = "POST_USER_INVITE_SUCCESS";
export const POST_USER_INVITE_FAILURE = "POST_USER_INVITE_FAILURE";

export const CANCEL_USER_INVITE = "CANCEL_USER_INVITE";
export const CANCEL_USER_INVITE_SUCCESS = "CANCEL_USER_INVITE_SUCCESS";
export const CANCEL_USER_INVITE_FAILURE = "CANCEL_USER_INVITE_FAILURE";

export const SET_OPEN_MODAL = "SET_OPEN_MODAL";
export const SET_CLOSE_MODAL = "SET_CLOSE_MODAL";

export const SET_OPEN_DIALOG = "SET_OPEN_DIALOG";
export const SET_CLOSE_DIALOG = "SET_CLOSE_DIALOG";
