export const FETCH_ADMIN_ORGANIZATION_LIST = "FETCH_ADMIN_ORGANIZATION_LIST";
export const FETCH_ADMIN_ORGANIZATION_LIST_SUCCESS =
  "FETCH_ADMIN_ORGANIZATION_LIST_SUCCESS";
export const FETCH_ADMIN_ORGANIZATION_LIST_FAILURE =
  "FETCH_ADMIN_ORGANIZATION_LIST_FAILURE";

export const FETCH_ADMIN_ORGANIZATION = "FETCH_ADMIN_ORGANIZATION";
export const FETCH_ADMIN_ORGANIZATION_SUCCESS =
  "FETCH_ADMIN_ORGANIZATION_SUCCESS";
export const FETCH_ADMIN_ORGANIZATION_FAILURE =
  "FETCH_ADMIN_ORGANIZATION_FAILURE";

export const FETCH_ADMIN_USER_LIST = "FETCH_ADMIN_USER_LIST";
export const FETCH_ADMIN_USER_LIST_SUCCESS = "FETCH_ADMIN_USER_LIST_SUCCESS";
export const FETCH_ADMIN_USER_LIST_FAILURE = "FETCH_ADMIN_USER_LIST_FAILURE";

export const FETCH_ADMIN_INVITE_LIST = "FETCH_ADMIN_INVITE_LIST";
export const FETCH_ADMIN_INVITE_LIST_SUCCESS =
  "FETCH_ADMIN_INVITE_LIST_SUCCESS";
export const FETCH_ADMIN_INVITE_LIST_FAILURE =
  "FETCH_ADMIN_INVITE_LIST_FAILURE";
