export const FETCH_ADMIN_ORGANIZATION_LIST = "FETCH_ADMIN_ORGANIZATION_LIST";
export const FETCH_ADMIN_ORGANIZATION_LIST_SUCCESS = "FETCH_ADMIN_ORGANIZATION_LIST_SUCCESS";
export const FETCH_ADMIN_ORGANIZATION_LIST_FAILURE = "FETCH_ADMIN_ORGANIZATION_LIST_FAILURE";
