export const FETCH_ADMIN_ORGANIZATION_LIST = "FETCH_ADMIN_ORGANIZATION_LIST";
export const FETCH_ADMIN_ORGANIZATION_LIST_SUCCESS =
  "FETCH_ADMIN_ORGANIZATION_LIST_SUCCESS";
export const FETCH_ADMIN_ORGANIZATION_LIST_FAILURE =
  "FETCH_ADMIN_ORGANIZATION_LIST_FAILURE";

export const FETCH_ADMIN_ORGANIZATION = "FETCH_ADMIN_ORGANIZATION";
export const FETCH_ADMIN_ORGANIZATION_SUCCESS =
  "FETCH_ADMIN_ORGANIZATION_SUCCESS";
export const FETCH_ADMIN_ORGANIZATION_FAILURE =
  "FETCH_ADMIN_ORGANIZATION_FAILURE";

export const FETCH_ADMIN_USER_LIST = "FETCH_ADMIN_USER_LIST";
export const FETCH_ADMIN_USER_LIST_SUCCESS = "FETCH_ADMIN_USER_LIST_SUCCESS";
export const FETCH_ADMIN_USER_LIST_FAILURE = "FETCH_ADMIN_USER_LIST_FAILURE";

export const FETCH_ADMIN_INVITE_LIST = "FETCH_ADMIN_INVITE_LIST";
export const FETCH_ADMIN_INVITE_LIST_SUCCESS =
  "FETCH_ADMIN_INVITE_LIST_SUCCESS";
export const FETCH_ADMIN_INVITE_LIST_FAILURE =
  "FETCH_ADMIN_INVITE_LIST_FAILURE";

export const POST_ADMIN_INVITE = "POST_ADMIN_INVITE";
export const POST_ADMIN_INVITE_SUCCESS = "POST_ADMIN_INVITE_SUCCESS";
export const POST_ADMIN_INVITE_FAILURE = "POST_ADMIN_INVITE_FAILURE";

export const CANCEL_ADMIN_INVITE = "CANCEL_ADMIN_INVITE";
export const CANCEL_ADMIN_INVITE_SUCCESS = "CANCEL_ADMIN_INVITE_SUCCESS";
export const CANCEL_ADMIN_INVITE_FAILURE = "CANCEL_ADMIN_INVITE_FAILURE";

export const FETCH_ADMIN_USER = "FETCH_ADMIN_USER";
export const FETCH_ADMIN_USER_SUCCESS = "FETCH_ADMIN_USER_SUCCESS";
export const FETCH_ADMIN_USER_FAILURE = "FETCH_ADMIN_USER_FAILURE";

export const DELETE_ADMIN_USER = "DELETE_ADMIN_USER";
export const DELETE_ADMIN_USER_SUCCESS = "DELETE_ADMIN_USER_SUCCESS";
export const DELETE_ADMIN_USER_FAILURE = "DELETE_ADMIN_USER_FAILURE";

export const ADMIN_SEND_POINTS_TO_USER = "ADMIN_SEND_POINTS_TO_USER";
export const ADMIN_SEND_POINTS_TO_USER_SUCCESS =
  "ADMIN_SEND_POINTS_TO_USER_SUCCESS";
export const ADMIN_SEND_POINTS_TO_USER_FAILURE =
  "ADMIN_SEND_POINTS_TO_USER_FAILURE";
